In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

In [3]:
print('a : ', a)
print('b : ', b)

a :  [1 2 3]
b :  [[1 2 3]
 [4 5 6]]


In [4]:
# .ndim : 배열의 차원을 알 수 있다.
print('a n_dimension : ', a.ndim)
print('b n_dimension : ', b.ndim)

a n_dimension :  1
b n_dimension :  2


In [5]:
# .shape : 배열의 사이즈를 알 수 있다.
print('a shape : ', a.shape)
print('b shape : ', b.shape)

a shape :  (3,)
b shape :  (2, 3)


In [6]:
# .size : 총 길이를 알 수 있다.
print('a size : ', a.size)
print('b size : ', b.size)

a size :  3
b size :  6


In [7]:
# .dtype : 데이터 type을 알 수 있다.
print('a dtype : ', a.dtype)
print('b dtype : ', b.dtype)

a dtype :  int32
b dtype :  int32


In [8]:
# .itemsize : 배열 요소의 바이트 크기
print('a itemsize : ', a.itemsize)
print('b itemsize : ', b.itemsize)

a itemsize :  4
b itemsize :  4


In [9]:
# np.array를 생성할 때 dtype으로 유형을 지정할 수 있다.
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [10]:
# np.zeros : 지정된 배열 모든 값에 0을 대입한다.
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# np.ones : 지정된 배열 모든 값에 1을 대입힌다.
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# np.empty : (값의 초기화를 수행하지 않고) 주어진 형태와 타입을 갖는 새로운 어레이를 반환한다.
np.empty((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# np.arrange : 주어진 간격으로 배열을 생성한다.
np.arange(1, 2, 0.3)

array([1. , 1.3, 1.6, 1.9])

In [14]:
# np.linspace : 주어진 간격만큼 배열을 나눈다.
np.linspace(1, 2, 7)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [15]:
zero = np.zeros((1,3))
one = np.ones((3,1))
print("zero : ", zero)
print("one : ", one)

zero :  [[0. 0. 0.]]
one :  [[1.]
 [1.]
 [1.]]


In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.arange(11, 22, 2)
print('a : ', a)
print('b : ', b)

a :  [[1 2 3]
 [4 5 6]]
b :  [11 13 15 17 19 21]


In [17]:
# .reshape은 데이터 배열을 바꾸는데 사용한다.
print('b shape : ', b.shape)
b = b.reshape((2,3))
print('b reshape : ', b.shape)

b shape :  (6,)
b reshape :  (2, 3)


In [24]:
# .vstack은 수직으로(vertically) 데이터들을 쌓아준다.
v = np.vstack((a, b, zero))
v

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [11., 13., 15.],
       [17., 19., 21.],
       [ 0.,  0.,  0.]])

In [25]:
# .hstack은 수평으로(horizontal) 데이터들을 쌓아준다. 
h = np.hstack((a, b))
h

array([[ 1,  2,  3, 11, 13, 15],
       [ 4,  5,  6, 17, 19, 21]])

In [27]:
# .vsplit은 수직으로 데이터들을 나눠준다.
np.vsplit(v, 5)

[array([[1., 2., 3.]]),
 array([[4., 5., 6.]]),
 array([[11., 13., 15.]]),
 array([[17., 19., 21.]]),
 array([[0., 0., 0.]])]

In [28]:
# .hsplit은 수평으로 데이터들을 나눠준다.
np.hsplit(h, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 13, 15],
        [17, 19, 21]])]

In [30]:
# 배열 인덱싱
data = np.arange(100, 200)
data

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [31]:
data[0]

100

In [33]:
every_five = np.arange(0, 100, 5)
every_five

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [34]:
data[every_five]

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [36]:
# 특정 shape의 배열을 생성한 뒤 인덱싱해주면 그 shape 형태로 값이 출력된다.
a = np.array([(1, 2), (10, 20)])
a

array([[ 1,  2],
       [10, 20]])

In [37]:
data[a]

array([[101, 102],
       [110, 120]])

In [38]:
print(data)
data.shape

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


(100,)

In [43]:
# reshape으로 10줄 마다 한 배열에 저장한다.
data_reshape = np.reshape(data, (10, -1))
print(data_reshape)
data_reshape.shape

[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


(10, 10)

In [44]:
data_reshape[2:, 1]

array([121, 131, 141, 151, 161, 171, 181, 191])

In [45]:
data_reshape[0, :]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [48]:
random_data = (np.random.random((5, 5)) - 0.5) * 100
random_data

array([[ 30.66500474,  27.21951099, -23.88844035,   2.94617715,
         -9.07281331],
       [-33.75028871,  41.91853738, -36.63813088, -36.68812173,
        -40.21822755],
       [ 19.6170258 ,   6.46578178,  19.83226453,  -0.64695314,
         45.56809401],
       [ 44.83589352,  42.86170903, -12.55419407,  30.32799246,
        -28.65253803],
       [-31.9709086 ,  43.59219705,  45.41649425, -10.5855545 ,
         34.25611347]])

In [53]:
print(np.min(random_data))
print(np.max(random_data))
print(np.average(random_data))
print(np.sum(random_data))
print(np.sin(random_data))

-40.21822754967599
45.568094011469576
6.834265011095769
170.85662527739422
[[-0.68231294  0.86981286  0.94717216  0.19417415 -0.34474268]
 [-0.72237482 -0.88093431  0.87283463  0.84735803 -0.58304931]
 [ 0.69431661  0.18158349  0.83200308 -0.60275804  0.99988749]
 [ 0.75364908 -0.90035652  0.01217624 -0.88566956  0.36925213]
 [-0.52692806 -0.38028099  0.99068482  0.91711294  0.29686285]]


In [55]:
arr = np.arange(1, 20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [56]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [57]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [59]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

In [60]:
arr + 50

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [61]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [62]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [63]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [64]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [65]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [66]:
np.sum(arr)

190

In [67]:
np.std(arr)

5.477225575051661

In [70]:
a = (np.random.random((5, 5)) - 0.5) * 100
a

array([[  1.58385727, -29.22128299,  41.9672174 , -30.11631928,
        -43.66495017],
       [ 15.94937754,  28.74884137, -10.97657682,   2.22432243,
        -20.93569169],
       [-15.19950475,  13.9350268 ,  14.46430712,   0.7111179 ,
         26.97146455],
       [-48.00847529, -36.65942718, -20.77549795,  37.72111473,
         18.21692131],
       [-29.80022089,  27.05676977,  23.49389635, -17.48715294,
        -16.56277577]])

In [72]:
# .floor : 각 원소 값보다 작거나 같은 가장 큰 정수 값 (바닥 값)으로 내림
np.floor(a)

array([[  1., -30.,  41., -31., -44.],
       [ 15.,  28., -11.,   2., -21.],
       [-16.,  13.,  14.,   0.,  26.],
       [-49., -37., -21.,  37.,  18.],
       [-30.,  27.,  23., -18., -17.]])

In [73]:
# .T : 전치행렬을 생성한다.
a.T

array([[  1.58385727,  15.94937754, -15.19950475, -48.00847529,
        -29.80022089],
       [-29.22128299,  28.74884137,  13.9350268 , -36.65942718,
         27.05676977],
       [ 41.9672174 , -10.97657682,  14.46430712, -20.77549795,
         23.49389635],
       [-30.11631928,   2.22432243,   0.7111179 ,  37.72111473,
        -17.48715294],
       [-43.66495017, -20.93569169,  26.97146455,  18.21692131,
        -16.56277577]])

In [74]:
# .dot : 행렬에 특정 값을 곱해준다. 행렬끼리의 곱도 가능
np.dot(a, -1)

array([[ -1.58385727,  29.22128299, -41.9672174 ,  30.11631928,
         43.66495017],
       [-15.94937754, -28.74884137,  10.97657682,  -2.22432243,
         20.93569169],
       [ 15.19950475, -13.9350268 , -14.46430712,  -0.7111179 ,
        -26.97146455],
       [ 48.00847529,  36.65942718,  20.77549795, -37.72111473,
        -18.21692131],
       [ 29.80022089, -27.05676977, -23.49389635,  17.48715294,
         16.56277577]])

In [75]:
# .random.random : 0~1까지의 난수 생성
np.random.random(20)

array([0.85885427, 0.22579881, 0.76834558, 0.51807745, 0.33287542,
       0.89738162, 0.95992775, 0.36825385, 0.15668434, 0.33565705,
       0.88573623, 0.0106284 , 0.06854584, 0.36604377, 0.82002807,
       0.07217147, 0.89072558, 0.81912405, 0.52908245, 0.82831371])

In [77]:
# .random.rand : 0~1까지의 난수를 shape에 맞게 생성
np.random.rand(3, 4)

array([[0.43540523, 0.70198753, 0.96482195, 0.66423049],
       [0.35901291, 0.88953814, 0.77709982, 0.93528009],
       [0.734311  , 0.82956604, 0.11210995, 0.20083516]])

In [78]:
# .random.randint : 특정 범위의 값을 특정 갯수만큼 생성
np.random.randint(0, 100, 20)

array([ 5, 29, 93, 48, 72,  3, 68, 64, 97, 41, 89, 67,  2, 51, 63, 61, 72,
       31, 89, 76])

In [79]:
# .random.permutation : 데이터를 섞는다.
np.random.permutation(a)

array([[ 15.94937754,  28.74884137, -10.97657682,   2.22432243,
        -20.93569169],
       [  1.58385727, -29.22128299,  41.9672174 , -30.11631928,
        -43.66495017],
       [-29.80022089,  27.05676977,  23.49389635, -17.48715294,
        -16.56277577],
       [-15.19950475,  13.9350268 ,  14.46430712,   0.7111179 ,
         26.97146455],
       [-48.00847529, -36.65942718, -20.77549795,  37.72111473,
         18.21692131]])